[package]
name = "handler"
version = "0.1.0"
edition = "2024"

[dependencies]
structure = { path = "../structure" }
function = { path = "../function" }
axum = "0.8.3"
rust_decimal = "1.37.1"
serde_json = "1.0.140"
