[package]
name = "function"
version = "0.1.0"
edition = "2024"

[dependencies]
structure = { path = "../structure" }
rand = "0.9.1"
rand_chacha = "0.9.0"
serde_json = "1.0.140"
rust_decimal = "1.37.1"
sha2 = "0.10.8"
hmac = "0.12.1"
hex = "0.4.3"
base64 = "0.22.1"
chrono = "0.4.41"